export type Rubric={id:string;title:string;max:number;criteria:string};
export type Experiment={id:string;title:string;week:string;summary:string;task:string;deliverables:string[];rubric:Rubric[];questions:string[];instructions:string;sourceFiles?:string[];grading?:'team'|'individual'|'none'};
export type CourseDraft={title:string;term:string;description:string;experiments:Experiment[];questions:string[]};
export function validateDraft(value:unknown):CourseDraft{const d=value as CourseDraft;if(!d||typeof d.title!=='string'||!d.title.trim()||d.title.length>160||!Array.isArray(d.experiments)||!d.experiments.length||d.experiments.length>20)throw Error('课程草案缺少标题或有效实验');if(!Array.isArray(d.questions)||d.questions.some(q=>typeof q!=='string'))throw Error('待确认事项格式不正确');const ids=new Set();for(const e of d.experiments){if(!e.id||ids.has(e.id)||!e.title||!e.task||!Array.isArray(e.deliverables)||!Array.isArray(e.rubric))throw Error('实验任务、提交清单或评分标准不完整');if(e.grading===undefined||e.grading===null)e.grading='team';else if(e.grading!=='team'&&e.grading!=='individual'&&e.grading!=='none')throw Error('判分方式无效');const noSubmit=e.grading==='none';if(!noSubmit&&!e.deliverables.length)throw Error('实验任务、提交清单或评分标准不完整');if(!noSubmit&&!e.rubric.length)throw Error('实验任务、提交清单或评分标准不完整');ids.add(e.id);const rids=new Set();let sum=0;for(const r of e.rubric){if(!r.id||rids.has(r.id)||!r.title||!r.criteria||!Number.isFinite(r.max)||r.max<=0)throw Error('评分项编号或分值无效');rids.add(r.id);sum+=r.max;}if(!noSubmit&&Math.abs(sum-100)>0.001)throw Error(`${e.title} 的评分总分应为 100 分`);if(noSubmit&&sum>0)throw Error(`${e.title} 无需提交，不应设置评分项`);}return d;}
export function validateAssessment(value:any,e:Experiment,curve=true){if(!value||!Array.isArray(value.items)||value.items.length!==e.rubric.length)throw Error('评分项数量不匹配');const seen=new Set();let total=0;for(const item of value.items){const r=e.rubric.find(r=>r.id===item.id);if(!r||seen.has(item.id)||!Number.isFinite(item.score)||item.score<0||item.score>r.max||typeof item.reason!=='string'||!item.reason.trim()||!Array.isArray(item.evidence)||!item.evidence.length||item.evidence.some((x:any)=>typeof x!=='string'||!x.trim()))throw Error('评分范围或证据不符合要求');seen.add(item.id);total+=item.score;}if(value.suggestions!==undefined&&(!Array.isArray(value.suggestions)||value.suggestions.length>6||value.suggestions.some((s:any)=>typeof s!=='string'||!s.trim()||s.length>500)))throw Error('改进建议格式无效');
 if(value.baseline===undefined)value.baseline=true;else if(typeof value.baseline!=='boolean')throw Error('baseline 标记无效');
 // 评分从宽政策：baseline（相关且有实质内容）的提交由平台映射到 60-100 区间——总分=60+0.4×原始分，各项=0.6×max+0.4×原始项分（合计保持一致，各项不超 max）；
 // 模型只负责如实按项给分与 baseline 判定，不自行校准。教师复核改分（curve=false）不做映射，判抄袭等低分是教师权利。
 let cents=Math.round(total*100);let curved=false;
 if(curve&&value.baseline&&cents<10000){curved=true;for(const item of value.items){const max=e.rubric.find((r:Rubric)=>r.id===item.id)!.max;item.score=Math.round((max*0.6+item.score*0.4)*100)/100;}cents=0;for(const item of value.items)cents+=Math.round(item.score*100);}
 const {questions:q0,...rest}=value;return {...rest,total:cents/100};}
export const statusNames:Record<string,string>={queued:'等待连接器',running:'正在核验',complete:'已完成',failed:'需处理',cancelled:'已取消',pending:'待接受',accepted:'已加入',declined:'已拒绝',revoked:'已撤销',open:'待复核',resolved:'已处理',draft:'草案',published:'已发布'};
