import type {Platform} from './platform';
import {initialCourse} from './seed';
import {validateDraft,validateAssessment} from './domain';
const now=()=>Date.now(); const id=()=>crypto.randomUUID(); const json=(x:any)=>JSON.stringify(x);const parse=(x:any,f:any=null)=>{try{return JSON.parse(x)}catch{return f}};
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');}
const email=(x:any)=>String(x||'').trim().toLowerCase();
function need(v:any,m='没有访问权限',status=403):asserts v{if(!v)throw Object.assign(Error(m),{status});}
function text(v:any,max=20000){need(typeof v==='string'&&v.trim().length>0&&v.length<=max,'文本为空或过长',400);return v.trim();}
function reply(x:any,status=200,headers:any={}){return new Response(json(x),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});}
export async function api(req:Request,env:Platform){
 const db=env.DB;const stmt=(s:string,...v:any[])=>db.prepare(s).bind(...v);const one=async(s:string,...v:any[])=>stmt(s,...v).first();const all=async(s:string,...v:any[])=>(await stmt(s,...v).all()).results;const run=async(s:string,...v:any[])=>stmt(s,...v).run();
 const url=new URL(req.url);const path=url.pathname.replace(/^\/api\/?/,'');const method=req.method;const local=env.LOCAL_DEV==='1'&&['localhost','127.0.0.1'].includes(url.hostname);
 const record=(actor:string,action:string,target:string,detail:any)=>stmt('INSERT INTO audit VALUES(?,?,?,?,?,?)',id(),actor,action,target,json(detail),now());
 const enqueue=(owner:string,kind:string,payload:any,courseId:string|null=null,teamId:string|null=null,jid=id())=>({id:jid,statement:stmt('INSERT INTO jobs(id,owner,courseId,teamId,kind,payload,created) VALUES(?,?,?,?,?,?,?)',jid,owner,courseId,teamId,kind,json(payload),now())});
 async function user(){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)course_session=([^;]+)/)?.[1];if(token){const u=await one('SELECT users.* FROM sessions JOIN users ON sessions.userId=users.id WHERE sessions.token=? AND sessions.expires>?',await hash(token),now());if(u)return u;}
  const trusted=email(req.headers.get('oai-authenticated-user-email'));const admins=String(env.ADMIN_EMAILS||'').split(',').map(email).filter(Boolean);
  // Dispatch identity is trusted only on the hosted runtime; allowlist grants teacher rights.
  if(!local&&trusted&&req.headers.get('oai-authenticated-user-id')&&admins.includes(trusted)){let u=await one('SELECT * FROM users WHERE email=?',trusted);if(!u){await run('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)',id(),trusted,'课程负责人','','teacher',now());u=await one('SELECT * FROM users WHERE email=?',trusted);}return u;}
  return null;
 }
 async function course(cid:string,u:any,teacher=false){const c=await one('SELECT * FROM courses WHERE id=?',cid);need(c,'课程不存在',404);if(teacher)need(u.role==='teacher'&&c.owner===u.id);else need(c.owner===u.id||await one('SELECT 1 FROM enrollments WHERE courseId=? AND userId=?',cid,u.id));return c;}
 async function team(tid:string,u:any,leader=false){const t=await one('SELECT * FROM teams WHERE id=?',tid);need(t,'小组不存在',404);const c=await course(t.courseId,u);if(c.owner!==u.id)need(leader?t.leader===u.id:await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',tid,u.id));return {t,c};}
 async function accessibleFile(fid:string,u:any){const f=await one('SELECT * FROM files WHERE id=?',fid);need(f,'文件不存在',404);const c=await course(f.courseId,u);need(f.owner===u.id||c.owner===u.id||f.visibility==='student'||(f.teamId&&await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',f.teamId,u.id)));return f;}
 async function snapshot(u:any){const cs=await all('SELECT DISTINCT courses.* FROM courses LEFT JOIN enrollments ON courses.id=enrollments.courseId WHERE courses.owner=? OR enrollments.userId=? ORDER BY courses.created',u.id,u.id);const cid=url.searchParams.get('course')||cs[0]?.id;const c=cs.find((c:any)=>c.id===cid);let extra:any={};if(c){const teacher=c.owner===u.id;const my=await one('SELECT teams.* FROM teams JOIN members ON teams.id=members.teamId WHERE members.userId=? AND members.courseId=?',u.id,c.id);const ts=teacher?await all('SELECT * FROM teams WHERE courseId=?',c.id):my?[my]:[];for(const t of ts)t.members=await all('SELECT users.id,users.name,users.email,users.studentNo FROM members JOIN users ON members.userId=users.id WHERE members.teamId=? ORDER BY members.slot',t.id);
   const release=c.publishedId?await one('SELECT * FROM releases WHERE id=?',c.publishedId):null;
   const inv=teacher?await all('SELECT invites.*,teams.name as teamName FROM invites JOIN teams ON invites.teamId=teams.id WHERE teams.courseId=?',c.id):await all('SELECT invites.*,teams.name as teamName FROM invites JOIN teams ON invites.teamId=teams.id WHERE teams.courseId=? AND (invites.email=? OR teams.leader=?)',c.id,u.email,u.id);
   const subs=teacher?await all('SELECT submissions.*,teams.name as teamName,jobs.status,jobs.error,grades.report,grades.published FROM submissions JOIN teams ON submissions.teamId=teams.id JOIN jobs ON submissions.jobId=jobs.id LEFT JOIN grades ON grades.submissionId=submissions.id WHERE submissions.courseId=? ORDER BY submissions.created DESC',c.id):await all('SELECT submissions.*,teams.name as teamName,jobs.status,jobs.error,grades.report,grades.published FROM submissions JOIN teams ON submissions.teamId=teams.id JOIN jobs ON submissions.jobId=jobs.id LEFT JOIN grades ON grades.submissionId=submissions.id WHERE submissions.courseId=? AND submissions.teamId=? ORDER BY submissions.created DESC',c.id,my?.id||'');
   for(const s of subs){s.superseded=s.mode==='formal'&&subs.some((x:any)=>x.teamId===s.teamId&&x.experimentId===s.experimentId&&x.mode==='formal'&&x.ordinal>s.ordinal);s.members=parse(s.members,[]);s.fileIds=parse(s.fileIds,[]);s.report=(teacher||s.mode==='practice'||s.published)?parse(s.report):null;s.answers=await all('SELECT answers.*,jobs.status,jobs.result FROM answers JOIN jobs ON answers.jobId=jobs.id WHERE answers.submissionId=?'+(teacher?'':' AND answers.userId=?'),s.id,...(teacher?[]:[u.id]));s.answers=s.answers.map((a:any)=>({...a,result:parse(a.result)}));}
   const fs=await all('SELECT id,owner,name,type,size,visibility,created,teamId FROM files WHERE courseId=?'+(teacher?'':' AND (owner=? OR visibility=\'student\' OR teamId=?)')+' ORDER BY created DESC',c.id,...(teacher?[]:[u.id,my?.id||'']));
   extra={selected:c.id,publishedDraft:teacher&&release?parse(release.content):null,draft:teacher?parse(c.draft):release?parse(release.content):null,release:release?{id:release.id,revision:release.revision,created:release.created}:null,teams:ts,myTeam:my?.id,invites:inv,submissions:subs,files:fs,messages:teacher?await all('SELECT * FROM messages WHERE courseId=? ORDER BY created',c.id):[],jobs:teacher?await all('SELECT id,kind,status,error,created FROM jobs WHERE courseId=? AND kind=\'draft\' ORDER BY created DESC LIMIT 30',c.id):[],appeals:teacher?await all('SELECT appeals.* FROM appeals JOIN submissions ON submissions.id=appeals.submissionId WHERE submissions.courseId=?',c.id):await all('SELECT * FROM appeals WHERE userId=?',u.id),students:teacher?await all('SELECT users.id,users.name,users.email,users.studentNo,members.teamId FROM enrollments JOIN users ON users.id=enrollments.userId LEFT JOIN members ON members.userId=users.id AND members.courseId=enrollments.courseId WHERE enrollments.courseId=?',c.id):[]};
  }
  const health=parse((await one('SELECT value FROM settings WHERE key=\'connector_health\''))?.value,{});return {user:u,pendingInvites:await all('SELECT invites.*,teams.name as teamName FROM invites JOIN teams ON teams.id=invites.teamId WHERE invites.email=? AND invites.status=\'pending\'',u.email),courses:cs.map((c:any)=>({...c,draft:undefined,joinCode:c.owner===u.id?c.joinCode:undefined})),...extra,health:{online:now()-Math.max(health.acpAt||0,health.mailAt||0)<90000,acp:now()-(health.acpAt||0)<90000,mail:now()-(health.mailAt||0)<90000},local};
 }
 try{
  need(db,'数据库尚未就绪',503);
  if(method!=='GET'&&!path.startsWith('connector/')){const origin=req.headers.get('origin');need(!origin||origin===url.origin,'请求来源不匹配');}
  if(path==='health')return reply({ok:true,service:'course-loop'});
  if(path==='auth/request'&&method==='POST'){
   const b:any=await req.json();const em=email(b.email);need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)&&em.length<254,'请输入有效邮箱',400);const old=await one('SELECT * FROM otps WHERE email=?',em);need(!old||now()-old.sent>60000,'请在一分钟后重试',429);const health=parse((await one('SELECT value FROM settings WHERE key=\'connector_health\''))?.value,{});need(local||(now()-(health.mailAt||0)<90000),'邮件服务尚未连接，请联系教师',503);
   const code=local&&env.DEV_EMAIL_CODE?env.DEV_EMAIL_CODE:String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');
   const mail=enqueue('system','email',{to:em,subject:'课序登录验证码',text:`你的验证码是 ${code}，10 分钟内有效。若非本人操作，请忽略。`});await db.batch([stmt('INSERT INTO otps VALUES(?,?,0,?,?) ON CONFLICT(email) DO UPDATE SET hash=excluded.hash,attempts=0,expires=excluded.expires,sent=excluded.sent',em,await hash(em+code),now()+600000,now()),mail.statement]);return reply({message:local?'本地开发验证码已配置，邮件未真实发送':'验证码已进入邮件投递队列'});
  }
  if(path==='auth/verify'&&method==='POST'){
   const b:any=await req.json();const em=email(b.email);const code=String(b.code||'');const o=await one('SELECT * FROM otps WHERE email=?',em);need(o&&o.expires>now()&&o.attempts<5,'验证码已失效，请重新获取',400);await run('UPDATE otps SET attempts=attempts+1 WHERE email=?',em);need(o.hash===await hash(em+code),'验证码不正确',400);const consumed=await stmt('DELETE FROM otps WHERE email=? AND hash=? AND expires>? AND attempts<=5 RETURNING email',em,o.hash,now()).first();need(consumed,'验证码已使用',400);
   const admins=String(env.ADMIN_EMAILS||'').split(',').map(email);let u=await one('SELECT * FROM users WHERE email=?',em);if(!u){need(b.name&&b.studentNo||admins.includes(em),'首次注册请填写姓名和学号',400);await run('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)',id(),em,text(b.name||'课程负责人',80),String(b.studentNo||'').slice(0,40),admins.includes(em)?'teacher':'student',now());u=await one('SELECT * FROM users WHERE email=?',em);}
   const token=id()+id();await run('INSERT INTO sessions VALUES(?,?,?)',await hash(token),u.id,now()+7*86400000);return reply({user:u},200,{'Set-Cookie':`course_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${url.protocol==='https:'?'; Secure':''}`});
  }
  if(path==='auth/logout'){const token=req.headers.get('cookie')?.match(/course_session=([^;]+)/)?.[1];if(token)await run('DELETE FROM sessions WHERE token=?',await hash(token));return reply({ok:true},200,{'Set-Cookie':'course_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
  // Connector calls use a separate bearer capability, never a student session.
  if(path.startsWith('connector/')){
   const secret=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';const stored=await one('SELECT value FROM settings WHERE key=\'connector_token\'');need(stored&&stored.value===await hash(secret),'连接器凭据无效',401);
   if(path==='connector/poll'&&method==='POST'){const b:any=await req.json();const h=parse((await one("SELECT value FROM settings WHERE key='connector_health'"))?.value,{});await run('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','connector_health',json({...h,...(b.acp?{acpAt:now()}:{}),...(b.mail?{mailAt:now()}: {})}));await run('UPDATE jobs SET status=\'failed\',error=\'连接器任务超时，请重试\' WHERE status=\'running\' AND expires<?',now());const kinds=[...(b.acp?['draft','grade','answer']:[]),...(b.mail?['email']:[])];if(!kinds.length)return reply({job:null});const lease=id();const job=await stmt(`UPDATE jobs SET status='running',lease=?,expires=?,attempts=attempts+1 WHERE id=(SELECT id FROM jobs WHERE status='queued' AND kind IN (${kinds.map(()=>'?').join(',')}) ORDER BY created LIMIT 1) AND status='queued' RETURNING *`,lease,now()+900000,...kinds).first();if(!job)return reply({job:null});const payload=parse(job.payload,{});const fids=payload.fileIds||[];const attachments=[];for(const fid of fids){const f=await one('SELECT id,name,type,size FROM files WHERE id=? AND courseId=?',fid,job.courseId);if(f)attachments.push(f);}return reply({job:{...job,payload,files:attachments}});}
   const parts=path.split('/');const jid=parts[2];const j=await one('SELECT * FROM jobs WHERE id=?',jid);need(j,'任务不存在',404);const lease=req.headers.get('x-job-lease');need(j.lease===lease&&j.status==='running'&&j.expires>now(),'任务租约已失效',409);
   if(parts[1]==='file'){const fid=parts[3];need(parse(j.payload,{}).fileIds?.includes(fid),'文件不属于任务');const f=await one('SELECT * FROM files WHERE id=?',fid);const obj=await env.FILES.get(f.key);need(obj,'文件不存在',404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream'}});}
   if(parts[1]==='heartbeat'){await run('UPDATE jobs SET expires=? WHERE id=?',now()+900000,j.id);const h=parse((await one("SELECT value FROM settings WHERE key='connector_health'"))?.value,{});await run("UPDATE settings SET value=? WHERE key='connector_health'",json({...h,[j.kind==='email'?'mailAt':'acpAt']:now()}));return reply({ok:true});}
   if(parts[1]==='finish'&&method==='POST'){
    const b:any=await req.json();const p=parse(j.payload,{});if(b.error){await run('UPDATE jobs SET status=\'failed\',error=? WHERE id=? AND lease=?',String(b.error).slice(0,2000),j.id,lease);return reply({ok:true});}
    const mutations=[];let result=b.result;
    if(j.kind==='draft'){const d=validateDraft(result.draft);const c=await one('SELECT * FROM courses WHERE id=?',j.courseId);need(c.revision===p.revision,'课程已变化，请重新发起分析',409);mutations.push(stmt('UPDATE courses SET draft=?,title=?,term=?,revision=revision+1 WHERE id=? AND revision=?',json(d),d.title,d.term||c.term,c.id,p.revision),stmt('INSERT INTO messages VALUES(?,?,?,?,?,?)',j.id,c.id,'assistant',text(result.message||'课程草案已更新，请预览后确认发布。'),json([]),now()));}
    if(j.kind==='grade'){result=validateAssessment(result,p.experiment);const s=await one('SELECT * FROM submissions WHERE jobId=?',j.id);const c=await one('SELECT * FROM courses WHERE id=?',s.courseId);mutations.push(stmt('INSERT INTO grades VALUES(?,?,?,?)',s.id,json(result),s.mode==='practice'||(c.autoPublish&&!result.needsReview)?1:0,now()));}
    if(j.kind==='answer'){need(result&&typeof result.feedback==='string'&&result.feedback.length>0,'个人核验缺少反馈',400);result={feedback:result.feedback,needsReview:!!result.needsReview};}
    if(j.kind==='email'){result={delivered:true};mutations.push(stmt('UPDATE jobs SET payload=? WHERE id=?',json({delivered:true}),j.id));}
    mutations.push(stmt('UPDATE jobs SET status=\'complete\',result=?,error=NULL WHERE id=? AND lease=? AND status=\'running\'',json(result),j.id,lease));await db.batch(mutations);return reply({ok:true});
   }return reply({error:'连接器操作不存在'},404);
  }
  const u=await user();
  if(path==='state')return reply(u?await snapshot(u):{user:null,courses:[],local});
  need(u,'请先登录',401);
  if(path==='courses'&&method==='POST'){need(u.role==='teacher');const b:any=await req.json();let d=structuredClone(initialCourse);if(b.copyId){const c=await course(b.copyId,u,true);d=parse(c.draft);}if(b.term)d.term=text(b.term,100);if(b.title)d.title=text(b.title,160);const cid=id();await run('INSERT INTO courses(id,owner,title,term,draft,joinCode,created) VALUES(?,?,?,?,?,?,?)',cid,u.id,d.title,d.term,json(d),id().replaceAll('-','').slice(0,10).toUpperCase(),now());return reply({id:cid});}
  if(path==='join'&&method==='POST'){const b:any=await req.json();const c=await one('SELECT * FROM courses WHERE joinCode=?',String(b.code||'').trim().toUpperCase());need(c,'课程邀请码无效',400);await run('INSERT OR IGNORE INTO enrollments VALUES(?,?)',c.id,u.id);return reply({id:c.id});}
  if(path==='pair'&&method==='POST'){need(u.role==='teacher');const token=id()+id();await run('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','connector_token',await hash(token));await record(u.id,'connector.rotate','connector',{}).run();return reply({token});}
  if(path==='upload'&&method==='POST'){const form=await req.formData();const cid=String(form.get('courseId')||'');const c=await course(cid,u);const f=form.get('file') as File;need(f&&typeof f.arrayBuffer==='function'&&f.size>0&&f.size<=20*1024*1024,'文件大小应在 1 字节至 20 MB 之间',400);need(/\.(md|txt|pdf|docx|zip|json|jsonl|csv|py|png|jpg|jpeg|mp4)$/i.test(f.name),'暂不支持该文件类型',400);const tid=String(form.get('teamId')||'');if(tid)await team(tid,u);const fid=id();const name=f.name.replace(/[\\/\x00-\x1f]/g,'_').slice(0,180);const visibility=c.owner===u.id&&form.get('visibility')==='student'?'student':'private';await env.FILES.put(fid,await f.arrayBuffer(),{httpMetadata:{contentType:f.type||'application/octet-stream'}});await run('INSERT INTO files VALUES(?,?,?,?,?,?,?,?,?,?)',fid,u.id,cid,tid||null,fid,name,f.type,f.size,visibility,now());return reply({id:fid,name});}
  if(path.startsWith('files/')&&method==='GET'){const f=await accessibleFile(path.split('/')[1],u);const obj=await env.FILES.get(f.key);need(obj,'文件不存在',404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'X-Content-Type-Options':'nosniff'}});}
  if(path==='file-visibility'&&method==='POST'){const b:any=await req.json();const f=await one('SELECT * FROM files WHERE id=?',b.id);need(f,'文件不存在',404);await course(f.courseId,u,true);need(!f.teamId,'学生成果不能公开为课程资料',400);await run('UPDATE files SET visibility=? WHERE id=?',b.shared?'student':'private',f.id);await record(u.id,'file.visibility',f.id,{shared:!!b.shared}).run();return reply({ok:true});}
  if(path==='chat'&&method==='POST'){const b:any=await req.json();const c=await course(b.courseId,u,true);need(!await one('SELECT 1 FROM jobs WHERE courseId=? AND kind=\'draft\' AND status IN (\'queued\',\'running\')',c.id),'上一条课程分析尚未完成，可取消后重试',409);const fids=Array.isArray(b.fileIds)?b.fileIds.slice(0,10):[];for(const fid of fids){const f=await accessibleFile(fid,u);need(f.courseId===c.id,'附件不属于本课程');}const history=await all('SELECT role,content FROM messages WHERE courseId=? ORDER BY created DESC LIMIT 20',c.id);const content=text(b.message);const job=enqueue(u.id,'draft',{draft:parse(c.draft),revision:c.revision,message:content,history:history.reverse(),fileIds:fids},c.id);await db.batch([stmt('INSERT INTO messages VALUES(?,?,?,?,?,?)',id(),c.id,'user',content,json(fids),now()),job.statement]);return reply({jobId:job.id});}
  if(path==='publish'&&method==='POST'){const b:any=await req.json();const c=await course(b.courseId,u,true);need(c.revision===b.revision,'草案已变化，请重新预览',409);const d=validateDraft(parse(c.draft));need(!d.questions.length&&!d.experiments.some(e=>e.questions?.length),'请先通过对话解决待确认事项',400);need(!await one('SELECT 1 FROM jobs WHERE courseId=? AND kind=\'draft\' AND status IN (\'queued\',\'running\')',c.id),'分析尚未完成，暂不能发布',409);const rid=id();await db.batch([stmt('INSERT INTO releases VALUES(?,?,?,?,?)',rid,c.id,c.revision,json(d),now()),stmt('UPDATE courses SET publishedId=? WHERE id=?',rid,c.id),record(u.id,'course.publish',c.id,{revision:c.revision})]);return reply({id:rid});}
  if(path==='course-settings'&&method==='POST'){const b:any=await req.json();const c=await course(b.courseId,u,true);const n=Number(b.maxSize);need(Number.isInteger(n)&&n>=1&&n<=16,'小组上限应为 1–16',400);const max=await one('SELECT COUNT(*) as n FROM members WHERE courseId=? GROUP BY teamId ORDER BY n DESC LIMIT 1',c.id);need(n>=(max?.n||0),'已有小组人数超过新上限',400);const deadline=b.deadline?Date.parse(b.deadline):null;need(deadline===null||Number.isFinite(deadline),'截止时间无效',400);await run('UPDATE courses SET maxSize=?,deadline=?,autoPublish=? WHERE id=?',n,deadline,b.autoPublish?1:0,c.id);return reply({ok:true});}
  if(path==='teams'&&method==='POST'){const b:any=await req.json();const c=await course(b.courseId,u);need(await one('SELECT 1 FROM enrollments WHERE courseId=? AND userId=?',c.id,u.id),'先加入课程',400);const tid=id();await db.batch([stmt('INSERT INTO teams VALUES(?,?,?,?,0,?)',tid,c.id,u.id,text(b.name,60),now()),stmt('INSERT INTO members VALUES(?,?,?,1)',c.id,tid,u.id)]);return reply({id:tid});}
  if(path==='invite'&&method==='POST'){const b:any=await req.json();const {t,c}=await team(b.teamId,u,true);need(!t.locked||c.owner===u.id,'正式提交后成员调整需教师处理',409);const em=email(b.email);need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em),'邮箱格式无效',400);need(!await one('SELECT 1 FROM invites WHERE teamId=? AND email=? AND status=\'pending\'',t.id,em),'已经有待接受邀请',409);const iv=id();const mail=enqueue(u.id,'email',{to:em,subject:`邀请你加入 ${t.name}`,text:`你收到课序小组 ${t.name} 的邀请。请使用此邮箱注册/登录，加入课程（邀请码：${c.joinCode}），在“我的 Team”接受邀请。网站：${url.origin}`},c.id,t.id);await db.batch([stmt('INSERT INTO invites VALUES(?,?,?,\'pending\',?)',iv,t.id,em,now()),mail.statement]);return reply({ok:true,message:'邀请已创建；邮件投递状态取决于邮件连接器，也可登录后直接查看。'});}
  if(path==='invite-action'&&method==='POST'){const b:any=await req.json();const iv=await one('SELECT * FROM invites WHERE id=?',b.id);need(iv&&iv.status==='pending','邀请已处理',409);const t=await one('SELECT * FROM teams WHERE id=?',iv.teamId);const c=await one('SELECT * FROM courses WHERE id=?',t.courseId);if(b.action==='revoke'){need(t.leader===u.id||c.owner===u.id);await run('UPDATE invites SET status=\'revoked\' WHERE id=? AND status=\'pending\'',iv.id);return reply({ok:true});}need(iv.email===u.email,'只能接受发给本人邮箱的邀请');if(b.action==='decline'){await run('UPDATE invites SET status=\'declined\' WHERE id=?',iv.id);return reply({ok:true});}need(b.action==='accept','操作无效',400);need(!t.locked,'正式提交后请联系教师调整成员',409);const seats=await all('SELECT slot FROM members WHERE teamId=?',t.id);let slot=1;while(seats.some((s:any)=>s.slot===slot))slot++;need(slot<=c.maxSize,'小组已满',409);await db.batch([stmt('INSERT OR IGNORE INTO enrollments VALUES(?,?)',c.id,u.id),stmt('INSERT INTO members SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM invites WHERE id=? AND status=\'pending\') AND EXISTS(SELECT 1 FROM teams WHERE id=? AND locked=0)',c.id,t.id,u.id,slot,iv.id,t.id),stmt('UPDATE invites SET status=\'accepted\' WHERE id=? AND EXISTS(SELECT 1 FROM members WHERE teamId=? AND userId=?)',iv.id,t.id,u.id)]);return reply({ok:true});}
  if(path==='team-action'&&method==='POST'){const b:any=await req.json();const {t,c}=await team(b.teamId,u);need(!t.locked||c.owner===u.id,'正式提交后成员调整需教师处理',409);if(b.action==='transfer'){need(t.leader===u.id||c.owner===u.id);need(await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',t.id,b.userId),'目标不是组员',400);await run('UPDATE teams SET leader=? WHERE id=?',b.userId,t.id);}else if(b.action==='leave'||b.action==='remove'){const target=b.action==='leave'?u.id:b.userId;need(target===u.id||c.owner===u.id);need(t.leader!==target,'组长请先转让负责人',400);await run('DELETE FROM members WHERE teamId=? AND userId=?',t.id,target);}else throw Error('未知操作');await record(u.id,'team.'+b.action,t.id,{target:b.userId||u.id}).run();return reply({ok:true});}
  if(path==='submit'&&method==='POST'){const b:any=await req.json();const {t,c}=await team(b.teamId,u);need(c.publishedId,'课程尚未发布',400);const mode=b.mode;need(['practice','formal'].includes(mode),'提交类型无效',400);if(mode==='formal'){need(t.leader===u.id,'由组长确认正式提交');need(!c.deadline||now()<=c.deadline,'已超过截止时间',400);}const r=await one('SELECT * FROM releases WHERE id=?',c.publishedId);const exp=parse(r.content).experiments.find((e:any)=>e.id===b.experimentId);need(exp,'实验不存在',400);need(Array.isArray(b.fileIds)&&b.fileIds.length>0&&b.fileIds.length<=20,'请上传作业材料',400);for(const fid of b.fileIds){const f=await accessibleFile(fid,u);need(f.teamId===t.id&&f.courseId===c.id,'文件不属于本组');}const last=await one('SELECT MAX(ordinal) as n FROM submissions WHERE teamId=? AND experimentId=? AND mode=?',t.id,exp.id,mode);const ordinal=(last?.n||0)+1;need(mode!=='formal'||ordinal<=c.maxFormal,'正式提交次数已用完',400);const mem=await all('SELECT users.id,users.name,users.email FROM members JOIN users ON members.userId=users.id WHERE members.teamId=?',t.id);const sid=id();const job=enqueue(u.id,'grade',{submissionId:sid,releaseId:r.id,revision:r.revision,experiment:exp,mode,fileIds:b.fileIds,note:String(b.note||'').slice(0,20000),members:mem},c.id,t.id);await db.batch([job.statement,stmt('INSERT INTO submissions VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',sid,c.id,t.id,exp.id,r.id,mode,ordinal,json(mem),json(b.fileIds),String(b.note||'').slice(0,20000),job.id,now()),...(mode==='formal'?[stmt('UPDATE teams SET locked=1 WHERE id=?',t.id)]:[])]);return reply({id:sid});}
  if(path==='answer'&&method==='POST'){const b:any=await req.json();const s=await one('SELECT * FROM submissions WHERE id=?',b.submissionId);need(s,'提交不存在',404);await course(s.courseId,u);need(parse(s.members,[]).some((m:any)=>m.id===u.id),'你不在正式成员快照中');const g=await one('SELECT * FROM grades WHERE submissionId=?',s.id);need(g&&parse(g.report).questions?.length,'当前没有追问',400);const content=text(b.content);const job=enqueue(u.id,'answer',{submissionId:s.id,questions:parse(g.report).questions,answer:content,note:s.note,fileIds:parse(s.fileIds),member:u.name},s.courseId,s.teamId);await db.batch([job.statement,stmt('INSERT INTO answers VALUES(?,?,?,?,?,?)',id(),s.id,u.id,content,job.id,now())]);return reply({ok:true});}
  if(path==='appeal'&&method==='POST'){const b:any=await req.json();const s=await one('SELECT * FROM submissions WHERE id=?',b.submissionId);need(s,'提交不存在',404);await team(s.teamId,u);const g=await one('SELECT * FROM grades WHERE submissionId=?',s.id);need(g&&(g.published||s.mode==='practice'),'评分尚未发布',400);await run('INSERT INTO appeals(id,submissionId,userId,content,created) VALUES(?,?,?,?,?)',id(),s.id,u.id,text(b.content),now());return reply({ok:true});}
  if(path==='grade-action'&&method==='POST'){const b:any=await req.json();const s=await one('SELECT * FROM submissions WHERE id=?',b.submissionId);need(s,'提交不存在',404);await course(s.courseId,u,true);const g=await one('SELECT * FROM grades WHERE submissionId=?',s.id);need(g,'尚无评分',400);let report=parse(g.report);const reason=text(b.reason);if(b.report){const r=await one('SELECT * FROM releases WHERE id=?',s.releaseId);const e=parse(r.content).experiments.find((e:any)=>e.id===s.experimentId);report=validateAssessment(b.report,e);}const mutations=[stmt('UPDATE grades SET report=?,published=1,updated=? WHERE submissionId=?',json(report),now(),s.id),record(u.id,'grade.review',s.id,{reason,before:parse(g.report),after:report})];if(b.appealId)mutations.push(stmt('UPDATE appeals SET status=\'resolved\',resolution=? WHERE id=? AND submissionId=?',reason,b.appealId,s.id));await db.batch(mutations);return reply({ok:true});}
  if(path==='job-action'&&method==='POST'){const b:any=await req.json();const j=await one('SELECT * FROM jobs WHERE id=?',b.id);need(j,'任务不存在',404);const c=j.courseId?await course(j.courseId,u):null;need(j.owner===u.id||c?.owner===u.id);need(j.kind!=='email','邮件由系统管理');if(b.action==='cancel')await run('UPDATE jobs SET status=\'cancelled\' WHERE id=? AND status IN (\'queued\',\'running\')',j.id);else {need(j.status==='failed','只能重试失败任务',409);if(j.kind==='draft'){const p=parse(j.payload);need(p.revision===c.revision,'草案已变更，请发送新消息',409);}await run('UPDATE jobs SET status=\'queued\',lease=NULL,error=NULL WHERE id=?',j.id);}return reply({ok:true});}
  return reply({error:'接口不存在'},404);
 }catch(e:any){const constraint=/UNIQUE constraint|constraint failed/i.test(e.message);return reply({error:constraint?'操作与当前状态冲突：你可能已加入小组、座位已占用或该版本已提交。请刷新后重试。':e.message||'服务异常'},e.status||(constraint?409:400));}
}
