import type {Platform} from './platform';
import {validateDraft,validateAssessment} from './domain';
const now=()=>Date.now(); const id=()=>crypto.randomUUID(); const json=(x:any)=>JSON.stringify(x);const parse=(x:any,f:any=null)=>{try{return JSON.parse(x)}catch{return f}};
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');}
const email=(x:any)=>String(x||'').trim().toLowerCase();
function need(v:any,m='没有访问权限',status=403):asserts v{if(!v)throw Object.assign(Error(m),{status});}
function text(v:any,max=20000){need(typeof v==='string'&&v.trim().length>0&&v.length<=max,'文本为空或过长',400);return v.trim();}
function reply(x:any,status=200,headers:any={}){return new Response(json(x),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});}
const ASSIST_GUIDE=`你是「小课」，课序平台的使用助手。用简洁中文回答，不知道就诚实说并建议联系教师或课程管理员，绝不编造平台功能。用户提改进意见时，感谢并引导对方点击面板上的「提改进意见」按钮记录，课程负责人会定期查阅。

平台使用指南：
- 角色：课程管理员维护课程与实验内容；教师选择课程开设课堂（每课堂独立邀请码），只看自己课堂的小组、提交与成绩；学生凭课堂邀请码加入课堂后组队做实验。
- 注册登录：邮箱+验证码；首次登录补充身份（学生/教师）与姓名，学生还要学号。
- 加入课堂：学生左侧栏「加入课堂」输入教师分享的课堂邀请码。
- Team：学生在「我的 Team」创建或接受邀请加入小组；组长邀请/转让/移除成员；每组可维护自己的 GitHub 仓库地址。
- 实验：每个实验最多提交 3 次——小组判分由组长代表小组提交，个人判分由学生本人提交；每次提交都会立即评分出分，最终成绩取最高分；截止时间由教师在课堂设置里定，教师保留修改成绩的权利。评分按评分项给分（百分制），平台会将相关且有效的提交校准到保底 60 分以上（60+0.4×评分），系统异常不会直接计零分。
- 成绩：每次提交立即评分发布，最终取最高分；学生对已发布成绩可申诉，需要澄清的内容在下次提交的说明里补充即可。
- 管理员在「连接与设置」可查看小课工作日志与 Pi/邮件连接状态。`;
export async function api(req:Request,env:Platform){
 const db=env.DB;const stmt=(s:string,...v:any[])=>db.prepare(s).bind(...v);const one=async(s:string,...v:any[])=>stmt(s,...v).first();const all=async(s:string,...v:any[])=>(await stmt(s,...v).all()).results;const run=async(s:string,...v:any[])=>stmt(s,...v).run();
 const url=new URL(req.url);const path=url.pathname.replace(/^\/api\/?/,'');const method=req.method;const local=env.LOCAL_DEV==='1'&&['localhost','127.0.0.1'].includes(url.hostname);
 const record=(actor:string,action:string,target:string,detail:any)=>stmt('INSERT INTO audit VALUES(?,?,?,?,?,?)',id(),actor,action,target,json(detail),now());
 const enqueue=(owner:string,kind:string,payload:any,courseId:string|null=null,classId:string|null=null,teamId:string|null=null,jid=id())=>({id:jid,statement:stmt('INSERT INTO jobs(id,owner,courseId,classId,teamId,kind,payload,created) VALUES(?,?,?,?,?,?,?,?)',jid,owner,courseId,classId,teamId,kind,json(payload),now())});
 const admins=()=>String(env.ADMIN_EMAILS||'').split(',').map(email).filter(Boolean);
 async function user(){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)course_session=([^;]+)/)?.[1];if(token){const u=await one('SELECT users.* FROM sessions JOIN users ON sessions.userId=users.id WHERE sessions.token=? AND sessions.expires>?',await hash(token),now());if(u)return u;}
  const trusted=email(req.headers.get('oai-authenticated-user-email'));
  // Dispatch identity is trusted only on the hosted runtime; allowlist grants admin rights.
  if(!local&&trusted&&req.headers.get('oai-authenticated-user-id')&&admins().includes(trusted)){let u=await one('SELECT * FROM users WHERE email=?',trusted);if(!u){await run('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)',id(),trusted,'课程管理员','','admin',now());u=await one('SELECT * FROM users WHERE email=?',trusted);}return u;}
  return null;
 }
 async function courseAdmin(cid:string,u:any){const c=await one('SELECT * FROM courses WHERE id=?',cid);need(c,'课程不存在',404);need(u.role==='admin'&&c.owner===u.id);return c;}
 async function cls(kid:string,u:any,owner=false){const k=await one('SELECT * FROM classes WHERE id=?',kid);need(k,'课堂不存在',404);if(owner)need(k.owner===u.id||u.role==='admin');else need(k.owner===u.id||u.role==='admin'||await one('SELECT 1 FROM enrollments WHERE classId=? AND userId=?',kid,u.id));return k;}
 async function team(tid:string,u:any,leader=false){const t=await one('SELECT * FROM teams WHERE id=?',tid);need(t,'小组不存在',404);const k=await one('SELECT * FROM classes WHERE id=?',t.classId);if(k.owner!==u.id&&u.role!=='admin')need(leader?t.leader===u.id:await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',tid,u.id));return {t,k};}
 async function accessibleFile(fid:string,u:any){const f=await one('SELECT * FROM files WHERE id=?',fid);need(f,'文件不存在',404);
  if(!f.classId)need(f.owner===u.id||u.role==='admin'||(f.visibility==='student'&&await one('SELECT 1 FROM classes k LEFT JOIN enrollments e ON e.classId=k.id AND e.userId=? WHERE k.courseId=? AND (k.owner=? OR e.userId IS NOT NULL)',u.id,f.courseId,u.id))); // 课程素材：上传者、admin，或共享后该课程任一课堂的师生
  else need(f.owner===u.id||u.role==='admin'||(f.teamId&&await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',f.teamId,u.id))||await one('SELECT 1 FROM classes WHERE id=? AND owner=?',f.classId,u.id)); // 课堂/小组文件：上传者、组员、课堂教师、admin
  return f;}
 const classCard=(x:any)=>({id:x.id,courseId:x.courseId,courseTitle:x.courseTitle,term:x.term,name:x.name,joinCode:x.joinCode,maxSize:x.maxSize,deadline:x.deadline,autoPublish:x.autoPublish,created:x.created});
 async function classDetail(k:any,u:any,tv:boolean){ // tv: 课堂教师（或 admin）视角
  const c=await one('SELECT * FROM courses WHERE id=?',k.courseId);const release=c.publishedId?await one('SELECT * FROM releases WHERE id=?',c.publishedId):null;
  const my=await one('SELECT teams.* FROM teams JOIN members ON teams.id=members.teamId WHERE members.userId=? AND members.classId=?',u.id,k.id);
  const ts=tv?await all('SELECT * FROM teams WHERE classId=?',k.id):my?[my]:[];for(const t of ts)t.members=await all('SELECT users.id,users.name,users.email,users.studentNo FROM members JOIN users ON members.userId=users.id WHERE members.teamId=? ORDER BY members.slot',t.id);
  const inv=tv?[]:await all('SELECT invites.*,teams.name as teamName FROM invites JOIN teams ON invites.teamId=teams.id WHERE teams.classId=? AND (invites.email=? OR teams.leader=?)',k.id,u.email,u.id);
  const subs=tv?await all('SELECT submissions.*,teams.name as teamName,jobs.status,jobs.error,grades.report,grades.published FROM submissions LEFT JOIN teams ON submissions.teamId=teams.id JOIN jobs ON submissions.jobId=jobs.id LEFT JOIN grades ON grades.submissionId=submissions.id WHERE submissions.classId=? ORDER BY submissions.created DESC',k.id):await all('SELECT submissions.*,teams.name as teamName,jobs.status,jobs.error,grades.report,grades.published FROM submissions LEFT JOIN teams ON submissions.teamId=teams.id JOIN jobs ON submissions.jobId=jobs.id LEFT JOIN grades ON grades.submissionId=submissions.id WHERE submissions.classId=? AND (submissions.teamId=? OR submissions.studentId=?) ORDER BY submissions.created DESC',k.id,my?.id||'',u.id);
  const ownerOf=(x:any)=>x.teamId||x.studentId;const bestOf=new Map();for(const x of subs){if(!x.report)continue;const tot=parse(x.report)?.total;if(!Number.isFinite(tot))continue;const key=x.experimentId+'|'+ownerOf(x);const b=bestOf.get(key);if(!b||tot>b.tot||(tot===b.tot&&x.ordinal>b.ordinal))bestOf.set(key,{id:x.id,tot,ordinal:x.ordinal});}
  for(const s of subs){s.superseded=subs.some((x:any)=>ownerOf(x)===ownerOf(s)&&x.experimentId===s.experimentId&&x.ordinal>s.ordinal);s.isBest=bestOf.get(s.experimentId+'|'+ownerOf(s))?.id===s.id;s.members=parse(s.members,[]);s.fileIds=parse(s.fileIds,[]);s.reviewPending=!tv&&!s.published&&!!s.report&&s.status==='complete';s.report=(tv||s.published)?parse(s.report):null;}
  const fs=tv?await all('SELECT id,owner,name,type,size,visibility,created,teamId FROM files WHERE classId=? OR (courseId=? AND classId IS NULL AND visibility=\'student\') ORDER BY created DESC',k.id,k.courseId):await all('SELECT id,owner,name,type,size,visibility,created,teamId FROM files WHERE (classId=? AND (owner=? OR teamId=?)) OR (courseId=? AND classId IS NULL AND visibility=\'student\') ORDER BY created DESC',k.id,u.id,my?.id||'',k.courseId);
  return {selected:k.id,course:{id:c.id,title:c.title,term:c.term},release:release?{id:release.id,revision:release.revision,created:release.created}:null,draft:release?parse(release.content):null,teams:ts,myTeam:tv?null:my?.id,invites:inv,submissions:subs,files:fs,appeals:tv?await all('SELECT appeals.*,users.name as userName,users.studentNo as userStudentNo,submissions.experimentId,submissions.ordinal,submissions.teamId,submissions.studentId,teams.name as teamName FROM appeals JOIN users ON users.id=appeals.userId JOIN submissions ON submissions.id=appeals.submissionId LEFT JOIN teams ON teams.id=submissions.teamId WHERE submissions.classId=? ORDER BY appeals.created DESC',k.id):await all('SELECT * FROM appeals WHERE userId=?',u.id),students:tv?await all('SELECT users.id,users.name,users.email,users.studentNo,members.teamId FROM enrollments JOIN users ON users.id=enrollments.userId LEFT JOIN members ON members.userId=users.id AND members.classId=enrollments.classId WHERE enrollments.classId=?',k.id):[]};
 }
 async function snapshot(u:any){
  const health=parse((await one('SELECT value FROM settings WHERE key=\'connector_health\''))?.value,{});const base={user:u,local,devCode:local?(env.DEV_EMAIL_CODE||''):'',health:{online:now()-Math.max(health.acpAt||0,health.mailAt||0)<90000,acp:now()-(health.acpAt||0)<90000,mail:now()-(health.mailAt||0)<90000,acpFound:health.acpFound??null,acpError:health.acpError??null,mailError:health.mailError??null},pendingInvites:await all('SELECT invites.*,teams.name as teamName FROM invites JOIN teams ON teams.id=invites.teamId WHERE invites.email=? AND invites.status=\'pending\'',u.email),assistHistory:(await all('SELECT id,role,content,created FROM assist WHERE userId=? ORDER BY created DESC LIMIT 50',u.id)).reverse()};
  if(u.role==='admin'){
   const cs=await all('SELECT courses.*,(SELECT COUNT(*) FROM classes WHERE classes.courseId=courses.id) AS classCount FROM courses WHERE owner=? ORDER BY created',u.id);const cid=url.searchParams.get('course')||cs[0]?.id;const c=cs.find((x:any)=>x.id===cid);let extra:any={};
   if(c){const release=c.publishedId?await one('SELECT * FROM releases WHERE id=?',c.publishedId):null;
    extra={selected:c.id,draft:parse(c.draft),publishedDraft:release?parse(release.content):null,release:release?{id:release.id,revision:release.revision,created:release.created}:null,messages:await all('SELECT * FROM messages WHERE courseId=? ORDER BY created',c.id),jobs:await all('SELECT id,kind,status,error,created FROM jobs WHERE courseId=? AND kind=\'draft\' ORDER BY created DESC LIMIT 30',c.id),files:await all('SELECT id,owner,name,type,size,visibility,created,teamId FROM files WHERE courseId=? AND classId IS NULL ORDER BY created DESC',c.id),courseClasses:await all('SELECT classes.id,classes.name,users.name as teacherName,classes.id=courses.primaryClassId as isPrimary,(SELECT COUNT(*) FROM enrollments WHERE enrollments.classId=classes.id) as students,(SELECT COUNT(*) FROM teams WHERE teams.classId=classes.id) as teams FROM classes JOIN users ON users.id=classes.owner JOIN courses ON courses.id=classes.courseId WHERE classes.courseId=? ORDER BY classes.created',c.id),primaryClassId:c.primaryClassId};}
   return {...base,courses:cs.map((x:any)=>({id:x.id,title:x.title,term:x.term,revision:x.revision,publishedId:x.publishedId,classCount:x.classCount,created:x.created})),classes:[],feedbackList:await all('SELECT feedback.id,feedback.content,feedback.status,feedback.created,users.name as userName,users.email as userEmail,users.role as userRole FROM feedback JOIN users ON users.id=feedback.userId ORDER BY feedback.created DESC'),...extra};
  }
  if(u.role==='teacher'){
   const courses=await all('SELECT id,title,term FROM courses ORDER BY created');
   const ks=await all('SELECT classes.*,courses.title as courseTitle,courses.term as term,courses.primaryClassId,(SELECT name FROM classes p WHERE p.id=courses.primaryClassId) as primaryName,(SELECT deadline FROM classes p WHERE p.id=courses.primaryClassId) as primaryDeadline FROM classes JOIN courses ON courses.id=classes.courseId WHERE classes.owner=? ORDER BY classes.created',u.id);
   const kid=url.searchParams.get('class')||ks[0]?.id;const k=ks.find((x:any)=>x.id===kid);return {...base,courses,classes:ks.map((x:any)=>({...classCard(x),isPrimary:x.id===x.primaryClassId,primaryName:x.primaryName,primaryDeadline:x.primaryDeadline})),...(k?await classDetail(k,u,true):{})};
  }
  const ks=await all('SELECT classes.*,courses.title as courseTitle,courses.term as term,users.name as teacherName FROM classes JOIN courses ON courses.id=classes.courseId JOIN users ON users.id=classes.owner JOIN enrollments ON enrollments.classId=classes.id AND enrollments.userId=? ORDER BY classes.created',u.id);
  const kid=url.searchParams.get('class')||ks[0]?.id;const k=ks.find((x:any)=>x.id===kid);return {...base,courses:[],classes:ks.map((x:any)=>({...classCard(x),joinCode:undefined,teacherName:x.teacherName})),...(k?await classDetail(k,u,false):{})};
 }
 try{
  need(db,'数据库尚未就绪',503);
  if(method!=='GET'&&!path.startsWith('connector/')){const origin=req.headers.get('origin');need(!origin||origin===url.origin,'请求来源不匹配');}
  if(path==='health')return reply({ok:true,service:'course-loop'});
  if(path==='auth/request'&&method==='POST'){
   const b:any=await req.json();const em=email(b.email);need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)&&em.length<254,'请输入有效邮箱',400);const old=await one('SELECT * FROM otps WHERE email=?',em);need(!old||now()-old.sent>60000,'请在一分钟后重试',429);const health=parse((await one('SELECT value FROM settings WHERE key=\'connector_health\''))?.value,{});need(local||(now()-(health.mailAt||0)<90000),'邮件服务尚未连接，请联系课程管理员',503);
   const lastFail=await one('SELECT error,created FROM jobs WHERE kind=\'email\' AND status=\'failed\' ORDER BY created DESC LIMIT 1');need(!(lastFail&&now()-lastFail.created<20*3600000&&/quota|rate.?limit|exceeded|too many|daily/i.test(lastFail.error||'')),'今日邮件发送额度已用完，请明天再试；如有急用请联系课程管理员。',429);
   const code=local&&env.DEV_EMAIL_CODE?env.DEV_EMAIL_CODE:String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');
   const mail=enqueue('system','email',{to:em,subject:'课序登录验证码',text:`你的验证码是 ${code}，10 分钟内有效。若非本人操作，请忽略。`});await db.batch([stmt('INSERT INTO otps VALUES(?,?,0,?,?) ON CONFLICT(email) DO UPDATE SET hash=excluded.hash,attempts=0,expires=excluded.expires,sent=excluded.sent',em,await hash(em+code),now()+600000,now()),mail.statement]);return reply({message:local?'本地开发验证码已配置，邮件未真实发送':'验证码已进入邮件投递队列'});
  }
  if(path==='auth/verify'&&method==='POST'){
   const b:any=await req.json();const em=email(b.email);const code=String(b.code||'');const o=await one('SELECT * FROM otps WHERE email=?',em);need(o&&o.expires>now()&&o.attempts<5,'验证码已失效，请重新获取',400);await run('UPDATE otps SET attempts=attempts+1 WHERE email=?',em);need(o.hash===await hash(em+code),'验证码不正确',400);const consumed=await stmt('DELETE FROM otps WHERE email=? AND hash=? AND expires>? AND attempts<=5 RETURNING email',em,o.hash,now()).first();need(consumed,'验证码已使用',400);
   let u=await one('SELECT * FROM users WHERE email=?',em);if(!u){const admin=admins().includes(em);await run('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)',id(),em,admin?'课程管理员':'','',admin?'admin':'pending',now());u=await one('SELECT * FROM users WHERE email=?',em);}
   const token=id()+id();await run('INSERT INTO sessions VALUES(?,?,?)',await hash(token),u.id,now()+7*86400000);return reply({user:u},200,{'Set-Cookie':`course_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${url.protocol==='https:'?'; Secure':''}`});
  }
  if(path==='auth/logout'){const token=req.headers.get('cookie')?.match(/course_session=([^;]+)/)?.[1];if(token)await run('DELETE FROM sessions WHERE token=?',await hash(token));return reply({ok:true},200,{'Set-Cookie':'course_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
  // Connector calls use a separate bearer capability, never a student session.
  if(path.startsWith('connector/')){
   const secret=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';const stored=await one('SELECT value FROM settings WHERE key=\'connector_token\'');need(stored&&stored.value===await hash(secret),'连接器凭据无效',401);
   if(path==='connector/poll'&&method==='POST'){const b:any=await req.json();const h=parse((await one("SELECT value FROM settings WHERE key='connector_health'"))?.value,{});await run('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','connector_health',json({...h,...(b.acp?{acpAt:now()}:{}),...(b.mail?{mailAt:now()}: {})}));await run('UPDATE jobs SET status=\'failed\',error=\'连接器任务超时，请重试\',finished=? WHERE status=\'running\' AND expires<?',now(),now());const kinds=[...(b.acp?['draft','grade']:[]),...(b.mail?['email']:[])];if(!kinds.length)return reply({job:null});const lease=id();const job=await stmt(`UPDATE jobs SET status='running',lease=?,expires=?,attempts=attempts+1 WHERE id=(SELECT id FROM jobs WHERE status='queued' AND kind IN (${kinds.map(()=>'?').join(',')}) ORDER BY created LIMIT 1) AND status='queued' RETURNING *`,lease,now()+900000,...kinds).first();if(!job)return reply({job:null});const payload=parse(job.payload,{});const fids=payload.fileIds||[];const attachments=[];for(const fid of fids){const f=await one('SELECT id,name,type,size FROM files WHERE id=? AND courseId=?',fid,job.courseId);if(f)attachments.push(f);}return reply({job:{...job,payload,files:attachments}});}
   const parts=path.split('/');const jid=parts[2];const j=await one('SELECT * FROM jobs WHERE id=?',jid);need(j,'任务不存在',404);const lease=req.headers.get('x-job-lease');need(j.lease===lease&&j.status==='running'&&j.expires>now(),'任务租约已失效',409);
   if(parts[1]==='file'){const fid=parts[3];need(parse(j.payload,{}).fileIds?.includes(fid),'文件不属于任务');const f=await one('SELECT * FROM files WHERE id=?',fid);const obj=await env.FILES.get(f.key);need(obj,'文件不存在',404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream'}});}
   if(parts[1]==='heartbeat'){await run('UPDATE jobs SET expires=? WHERE id=?',now()+900000,j.id);const h=parse((await one("SELECT value FROM settings WHERE key='connector_health'"))?.value,{});await run("UPDATE settings SET value=? WHERE key='connector_health'",json({...h,[j.kind==='email'?'mailAt':'acpAt']:now()}));return reply({ok:true});}
   if(parts[1]==='finish'&&method==='POST'){
    const b:any=await req.json();const p=parse(j.payload,{});if(b.error){await run('UPDATE jobs SET status=\'failed\',error=?,finished=? WHERE id=? AND lease=?',String(b.error).slice(0,2000),now(),j.id,lease);return reply({ok:true});}
    const mutations=[];let result=b.result;
    if(j.kind==='draft'){const d=validateDraft(result.draft);const c=await one('SELECT * FROM courses WHERE id=?',j.courseId);need(c.revision===p.revision,'课程已变化，请重新发起分析',409);mutations.push(stmt('UPDATE courses SET draft=?,title=?,term=?,revision=revision+1 WHERE id=? AND revision=?',json(d),d.title,d.term||c.term,c.id,p.revision),stmt('INSERT INTO messages VALUES(?,?,?,?,?,?)',j.id,c.id,'assistant',text(result.message||'课程草案已更新，请预览后确认发布。'),json([]),now()));}
    if(j.kind==='grade'){result=validateAssessment(result,p.experiment);const s=await one('SELECT * FROM submissions WHERE jobId=?',j.id);mutations.push(stmt('INSERT INTO grades VALUES(?,?,?,?)',s.id,json(result),1,now()));}
    if(j.kind==='email'){result={delivered:true};mutations.push(stmt('UPDATE jobs SET payload=? WHERE id=?',json({delivered:true}),j.id));}
    mutations.push(stmt('UPDATE jobs SET status=\'complete\',result=?,error=NULL,finished=? WHERE id=? AND lease=? AND status=\'running\'',json(result),now(),j.id,lease));await db.batch(mutations);return reply({ok:true});
   }return reply({error:'连接器操作不存在'},404);
  }
  const u=await user();
  if(path==='state')return reply(u?await snapshot(u):{user:null,courses:[],classes:[],local,devCode:local?(env.DEV_EMAIL_CODE||''):''});
  need(u,'请先登录',401);
  if(path==='auth/profile'&&method==='POST'){const b:any=await req.json();need(u.role==='pending','身份信息已完善',409);need(b.role==='teacher'||b.role==='student','身份类型无效',400);const name=text(b.name,80);const sn=b.role==='student'?text(b.studentNo,40):'';await run('UPDATE users SET role=?,name=?,studentNo=? WHERE id=?',b.role,name,sn,u.id);return reply({user:{...u,role:b.role,name,studentNo:sn}});}
  need(u.role!=='pending','请先完善个人信息',403);
  if(path==='job-log'&&method==='GET'){need(u.role==='admin');const page=Math.max(1,Number(url.searchParams.get('page'))||1);const size=20;const total=(await one('SELECT COUNT(*) n FROM jobs'))?.n||0;const items=await all('SELECT id,kind,status,error,attempts,created,finished FROM jobs ORDER BY created DESC LIMIT ? OFFSET ?',size,(page-1)*size);return reply({items,total,page,pageSize:size});}
  if(path==='assist'&&method==='POST'){const b:any=await req.json();const content=text(b.message);await run('INSERT INTO assist VALUES(?,?,?,?,?)',id(),u.id,'user',content,now());
   const history=(await all('SELECT role,content FROM assist WHERE userId=? ORDER BY created DESC LIMIT 20',u.id)).reverse();
   need(env.runAssist,'小课暂时不可用：未检测到 Pi。你可以先用「提改进意见」记录问题，或稍后再试。',503);
   const prompt=ASSIST_GUIDE+'\n\n对话历史（含用户最新问题）：\n'+history.map((h:any)=>(h.role==='user'?'用户':'小课')+'：'+h.content).join('\n')+'\n\n请用简洁中文回答用户最新的问题。';
   const answer=String(await env.runAssist(prompt)||'').trim();need(answer,'小课没有返回内容，请稍后再试。',503);
   await run('INSERT INTO assist VALUES(?,?,?,?,?)',id(),u.id,'assistant',answer,now());return reply({reply:answer});}
  if(path==='feedback'&&method==='POST'){const b:any=await req.json();await run('INSERT INTO feedback VALUES(?,?,?,?,?)',id(),u.id,text(b.content,2000),'open',now());return reply({ok:true});}
  if(path==='feedback-action'&&method==='POST'){need(u.role==='admin');const b:any=await req.json();need(b.action==='close'||b.action==='open','操作无效',400);const f=await one('SELECT * FROM feedback WHERE id=?',String(b.id||''));need(f,'意见不存在',404);await run('UPDATE feedback SET status=? WHERE id=?',b.action==='close'?'closed':'open',f.id);await record(u.id,'feedback.'+b.action,f.id,{}).run();return reply({ok:true});}
  if(path==='courses'&&method==='POST'){need(u.role==='admin');const b:any=await req.json();let d:any;if(b.copyId){const c=await courseAdmin(b.copyId,u);d=parse(c.draft);}else d={title:'未命名课程',term:'',description:'',experiments:[],questions:[]};if(b.term)d.term=text(b.term,100);if(b.title)d.title=text(b.title,160);const cid=id();await run('INSERT INTO courses(id,owner,title,term,draft,created) VALUES(?,?,?,?,?,?)',cid,u.id,d.title,d.term,json(d),now());return reply({id:cid});}
  if(path==='course-delete'&&method==='POST'){const b:any=await req.json();const c=await courseAdmin(String(b.courseId||''),u);need(!await one('SELECT 1 FROM classes WHERE courseId=?',c.id),'该课程下已有老师开设课堂，不能删除',409);const fs=await all('SELECT key FROM files WHERE courseId=? AND classId IS NULL',c.id);for(const f of fs)await env.FILES.delete?.(f.key).catch(()=>{});await db.batch([stmt('DELETE FROM files WHERE courseId=? AND classId IS NULL',c.id),stmt('DELETE FROM messages WHERE courseId=?',c.id),stmt('DELETE FROM releases WHERE courseId=?',c.id),stmt('DELETE FROM jobs WHERE courseId=? AND classId IS NULL',c.id),stmt('DELETE FROM courses WHERE id=?',c.id),record(u.id,'course.delete',c.id,{title:c.title})]);return reply({ok:true});}
  if(path==='course-export'&&method==='GET'){const c=await courseAdmin(String(url.searchParams.get('course')||''),u);const d=parse(c.draft);const payload=JSON.stringify({format:'course-loop-course',version:1,exported:now(),course:d},null,2);const name=encodeURIComponent((d.title||'course').replace(/[\\/\x00-\x1f]/g,'_'))+'.json';return new Response(payload,{headers:{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename*=UTF-8''${name}`,'Cache-Control':'no-store'}});}
  if(path==='course-import'&&method==='POST'){need(u.role==='admin');const b:any=await req.json();const raw=b.course;need(raw&&typeof raw==='object','课程数据无效',400);let d:any;if(Array.isArray(raw.experiments)&&raw.experiments.length)d=validateDraft(raw);else{need(typeof raw.title==='string'&&raw.title.trim(),'课程数据缺少标题或实验',400);d={title:text(raw.title,160),term:String(raw.term||'').slice(0,100),description:String(raw.description||'').slice(0,20000),experiments:[],questions:[]};}if(b.title)d.title=text(b.title,160);const cid=id();await run('INSERT INTO courses(id,owner,title,term,draft,created) VALUES(?,?,?,?,?,?)',cid,u.id,d.title,d.term,json(d),now());await record(u.id,'course.import',cid,{title:d.title}).run();return reply({id:cid});}
  if(path==='course-primary'&&method==='POST'){const b:any=await req.json();const c=await courseAdmin(String(b.courseId||''),u);const kid=String(b.classId||'');if(kid){const k=await one('SELECT * FROM classes WHERE id=?',kid);need(k&&k.courseId===c.id,'课堂不属于该课程',400);}await run('UPDATE courses SET primaryClassId=? WHERE id=?',kid||null,c.id);await record(u.id,'course.primary',c.id,{classId:kid||null}).run();return reply({ok:true});}
  if(path==='classes'&&method==='POST'){need(u.role==='teacher');const b:any=await req.json();const c=await one('SELECT * FROM courses WHERE id=?',String(b.courseId||''));need(c,'课程不存在',404);const name=b.name?text(b.name,60):'未命名课堂';const kid=id();let code='';for(let i=0;i<5;i++){code=id().replaceAll('-','').slice(0,10).toUpperCase();if(!await one('SELECT 1 FROM classes WHERE joinCode=?',code))break;}await run('INSERT INTO classes(id,courseId,owner,name,joinCode,created) VALUES(?,?,?,?,?,?)',kid,c.id,u.id,name,code,now());return reply({id:kid,joinCode:code});}
  if(path==='join'&&method==='POST'){need(u.role==='student');const b:any=await req.json();const k=await one('SELECT * FROM classes WHERE joinCode=?',String(b.code||'').trim().toUpperCase());need(k,'课堂邀请码无效',400);await run('INSERT OR IGNORE INTO enrollments VALUES(?,?)',k.id,u.id);return reply({id:k.id});}
  if(path==='pair'&&method==='POST'){need(u.role==='admin');const token=id()+id();await run('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','connector_token',await hash(token));await record(u.id,'connector.rotate','connector',{}).run();return reply({token});}
  if(path==='upload'&&method==='POST'){const form=await req.formData();const cid=String(form.get('courseId')||'');const kid=String(form.get('classId')||'');const tid=String(form.get('teamId')||'');need(!!cid!==!!kid,'文件必须归属一门课程或一个课堂',400);let courseId=cid,classId:string|null=null,material=false;
   if(cid){await courseAdmin(cid,u);need(!tid,'课程素材不属于小组',400);material=true;}
   else{const k=await one('SELECT * FROM classes WHERE id=?',kid);need(k,'课堂不存在',404);need(k.owner===u.id||u.role==='admin'||await one('SELECT 1 FROM enrollments WHERE classId=? AND userId=?',kid,u.id));courseId=k.courseId;classId=kid;if(tid){const tk=await team(tid,u);need(tk.k.id===kid,'小组不属于该课堂',400);}}
   const f=form.get('file') as File;need(f&&typeof f.arrayBuffer==='function'&&f.size>0,'请选择要上传的文件',400);need(f.size<=(classId?5*1024*1024:20*1024*1024),classId?'单个作业文件不能超过 5 MB，请压缩后分批上传':'文件大小应在 1 字节至 20 MB 之间',400);need(/\.(md|txt|pdf|docx|zip|json|jsonl|csv|py|png|jpg|jpeg|mp4)$/i.test(f.name),'暂不支持该文件类型',400);const fid=id();const name=f.name.replace(/[\\/\x00-\x1f]/g,'_').slice(0,180);const visibility=material&&form.get('visibility')==='student'?'student':'private';await env.FILES.put(fid,await f.arrayBuffer(),{httpMetadata:{contentType:f.type||'application/octet-stream'}});await run('INSERT INTO files(id,owner,courseId,classId,teamId,key,name,type,size,visibility,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)',fid,u.id,courseId,classId,tid||null,fid,name,f.type,f.size,visibility,now());return reply({id:fid,name});}
  if(path.startsWith('files/')&&method==='GET'){const f=await accessibleFile(path.split('/')[1],u);const obj=await env.FILES.get(f.key);need(obj,'文件不存在',404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'X-Content-Type-Options':'nosniff'}});}
  if(path==='file-visibility'&&method==='POST'){const b:any=await req.json();const f=await one('SELECT * FROM files WHERE id=?',b.id);need(f,'文件不存在',404);await courseAdmin(f.courseId,u);need(!f.classId,'课堂文件不能公开为课程素材',400);await run('UPDATE files SET visibility=? WHERE id=?',b.shared?'student':'private',f.id);await record(u.id,'file.visibility',f.id,{shared:!!b.shared}).run();return reply({ok:true});}
  if(path==='file-delete'&&method==='POST'){const b:any=await req.json();const f=await one('SELECT * FROM files WHERE id=?',b.id);need(f,'文件不存在',404);await courseAdmin(f.courseId,u);need(!f.classId,'课堂与作业文件属于教学记录，不能删除',400);await env.FILES.delete?.(f.key).catch(()=>{});await run('DELETE FROM files WHERE id=?',f.id);await record(u.id,'file.delete',f.id,{name:f.name}).run();return reply({ok:true});}
  if(path==='chat'&&method==='POST'){const b:any=await req.json();const c=await courseAdmin(b.courseId,u);need(!await one('SELECT 1 FROM jobs WHERE courseId=? AND kind=\'draft\' AND status IN (\'queued\',\'running\')',c.id),'上一条课程分析尚未完成，可取消后重试',409);const fids=Array.isArray(b.fileIds)?b.fileIds.slice(0,10):[];for(const fid of fids){const f=await accessibleFile(fid,u);need(f.courseId===c.id&&!f.classId,'附件不属于本课程素材');}const history=await all('SELECT role,content FROM messages WHERE courseId=? ORDER BY created DESC LIMIT 20',c.id);const content=text(b.message);const job=enqueue(u.id,'draft',{draft:parse(c.draft),revision:c.revision,message:content,history:history.reverse(),fileIds:fids},c.id);await db.batch([stmt('INSERT INTO messages VALUES(?,?,?,?,?,?)',id(),c.id,'user',content,json(fids),now()),job.statement]);return reply({jobId:job.id});}
  if(path==='publish'&&method==='POST'){const b:any=await req.json();const c=await courseAdmin(b.courseId,u);need(c.revision===b.revision,'草案已变化，请重新预览',409);const d=validateDraft(parse(c.draft));need(!d.questions.length&&!d.experiments.some(e=>e.questions?.length),'请先通过对话解决待确认事项',400);need(!await one('SELECT 1 FROM jobs WHERE courseId=? AND kind=\'draft\' AND status IN (\'queued\',\'running\')',c.id),'分析尚未完成，暂不能发布',409);const rid=id();await db.batch([stmt('INSERT INTO releases VALUES(?,?,?,?,?)',rid,c.id,c.revision,json(d),now()),stmt('UPDATE courses SET publishedId=? WHERE id=?',rid,c.id),record(u.id,'course.publish',c.id,{revision:c.revision})]);return reply({id:rid});}
  if(path==='class-settings'&&method==='POST'){const b:any=await req.json();const k=await cls(b.classId,u,true);const n=Number(b.maxSize);need(Number.isInteger(n)&&n>=1&&n<=16,'小组上限应为 1–16',400);const max=await one('SELECT COUNT(*) as n FROM members WHERE classId=? GROUP BY teamId ORDER BY n DESC LIMIT 1',k.id);need(n>=(max?.n||0),'已有小组人数超过新上限',400);const deadline=b.deadline?Date.parse(b.deadline):null;need(deadline===null||Number.isFinite(deadline),'截止时间无效',400);await run('UPDATE classes SET maxSize=?,deadline=?,autoPublish=? WHERE id=?',n,deadline,b.autoPublish?1:0,k.id);return reply({ok:true});}
  if(path==='teams'&&method==='POST'){const b:any=await req.json();const k=await one('SELECT * FROM classes WHERE id=?',String(b.classId||''));need(k,'课堂不存在',404);need(await one('SELECT 1 FROM enrollments WHERE classId=? AND userId=?',k.id,u.id),'先加入课堂',400);const tid=id();await db.batch([stmt('INSERT INTO teams(id,classId,leader,name,locked,created) VALUES(?,?,?,?,0,?)',tid,k.id,u.id,text(b.name,60),now()),stmt('INSERT INTO members(classId,teamId,userId,slot) VALUES(?,?,?,1)',k.id,tid,u.id)]);return reply({id:tid});}
  if(path==='invite'&&method==='POST'){const b:any=await req.json();const {t,k}=await team(b.teamId,u);need(t.leader===u.id,'仅组长可以邀请新成员');const em=email(b.email);need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em),'邮箱格式无效',400);need(!await one('SELECT 1 FROM invites WHERE teamId=? AND email=? AND status=\'pending\'',t.id,em),'已经有待接受邀请',409);const iv=id();const mail=enqueue(u.id,'email',{to:em,subject:`邀请你加入 ${t.name}`,text:`你收到课序小组 ${t.name} 的邀请。请使用此邮箱注册/登录，加入课堂（邀请码：${k.joinCode}），在“我的 Team”接受邀请。网站：${url.origin}`},k.courseId,k.id,t.id);await db.batch([stmt('INSERT INTO invites VALUES(?,?,?,\'pending\',?)',iv,t.id,em,now()),mail.statement]);return reply({ok:true,message:'邀请已创建；邮件投递状态取决于邮件连接器，也可登录后直接查看。'});}
  if(path==='invite-action'&&method==='POST'){const b:any=await req.json();const iv=await one('SELECT * FROM invites WHERE id=?',b.id);need(iv&&iv.status==='pending','邀请已处理',409);const t=await one('SELECT * FROM teams WHERE id=?',iv.teamId);const k=await one('SELECT * FROM classes WHERE id=?',t.classId);if(b.action==='revoke'){need(t.leader===u.id,'仅组长可以撤销邀请');await run('UPDATE invites SET status=\'revoked\' WHERE id=? AND status=\'pending\'',iv.id);return reply({ok:true});}need(iv.email===u.email,'只能接受发给本人邮箱的邀请');if(b.action==='decline'){await run('UPDATE invites SET status=\'declined\' WHERE id=?',iv.id);return reply({ok:true});}need(b.action==='accept','操作无效',400);const seats=await all('SELECT slot FROM members WHERE teamId=?',t.id);let slot=1;while(seats.some((s:any)=>s.slot===slot))slot++;need(slot<=k.maxSize,'小组已满',409);await db.batch([stmt('INSERT OR IGNORE INTO enrollments VALUES(?,?)',k.id,u.id),stmt('INSERT INTO members SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM invites WHERE id=? AND status=\'pending\')',k.id,t.id,u.id,slot,iv.id),stmt('UPDATE invites SET status=\'accepted\' WHERE id=? AND EXISTS(SELECT 1 FROM members WHERE teamId=? AND userId=?)',iv.id,t.id,u.id)]);return reply({ok:true});}
  if(path==='team-action'&&method==='POST'){const b:any=await req.json();const {t}=await team(b.teamId,u);if(b.action==='transfer'){need(t.leader===u.id,'仅组长可以转让负责人');need(await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',t.id,b.userId),'目标不是组员',400);await run('UPDATE teams SET leader=? WHERE id=?',b.userId,t.id);}else if(b.action==='rename'){need(t.leader===u.id,'仅组长可以修改小组名称');const name=text(b.name,60);need(name,'请输入小组名称',400);await run('UPDATE teams SET name=? WHERE id=?',name,t.id);}else if(b.action==='remove'){need(t.leader===u.id,'仅组长可以移除组员');need(b.userId!==t.leader,'组长请先转让负责人',400);need(await one('SELECT 1 FROM members WHERE teamId=? AND userId=?',t.id,b.userId),'目标不是组员',400);await run('DELETE FROM members WHERE teamId=? AND userId=?',t.id,b.userId);}else if(b.action==='leave'){need(t.leader!==u.id,'组长请先转让负责人',400);await run('DELETE FROM members WHERE teamId=? AND userId=?',t.id,u.id);}else throw Error('未知操作');await record(u.id,'team.'+b.action,t.id,{target:b.userId||u.id}).run();return reply({ok:true});}
  if(path==='team-repo'&&method==='POST'){const b:any=await req.json();const {t}=await team(b.teamId,u);let repo=String(b.repo||'').trim();need(repo===''||/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/?$/.test(repo),'请输入 GitHub 仓库地址，例如 https://github.com/owner/repo',400);repo=repo.replace(/\/+$/,'');await run('UPDATE teams SET repo=? WHERE id=?',repo,t.id);await record(u.id,'team.repo',t.id,{repo}).run();return reply({ok:true});}
  if(path==='submit'&&method==='POST'){const b:any=await req.json();need(Array.isArray(b.fileIds)&&b.fileIds.length>0&&b.fileIds.length<=20,'请上传作业材料',400);const fs:any[]=[];for(const fid of b.fileIds)fs.push(await accessibleFile(fid,u));const kid=fs[0].classId;need(kid&&fs.every((f:any)=>f.classId===kid),'文件不属于同一课堂',400);const k=await one('SELECT * FROM classes WHERE id=?',kid);need(k,'课堂不存在',404);need(await one('SELECT 1 FROM enrollments WHERE classId=? AND userId=?',kid,u.id),'你不在本课堂中',403);const c=await one('SELECT * FROM courses WHERE id=?',k.courseId);need(c.publishedId,'课程尚未发布',400);const pc=c.primaryClassId?await one('SELECT deadline FROM classes WHERE id=?',c.primaryClassId):null;const dl=pc?pc.deadline:k.deadline;need(!dl||now()<=dl,'已超过截止时间',400);const r=await one('SELECT * FROM releases WHERE id=?',c.publishedId);const exp=parse(r.content).experiments.find((e:any)=>e.id===b.experimentId);need(exp,'实验不存在',400);need(exp.grading!=='none','该实验无需提交，不计成绩',400);const individual=exp.grading==='individual';let t:any=null,mem:any[];
   if(individual){for(const f of fs)need(f.owner===u.id,'文件不属于本人',403);mem=[{id:u.id,name:u.name,email:u.email}];}
   else{t=await one('SELECT teams.* FROM teams JOIN members ON teams.id=members.teamId WHERE members.userId=? AND members.classId=?',u.id,k.id);need(t,'请先加入本课堂的小组',400);need(t.leader===u.id,'由组长代表小组提交');for(const f of fs)need(f.teamId===t.id,'文件不属于本组',403);mem=await all('SELECT users.id,users.name,users.email FROM members JOIN users ON members.userId=users.id WHERE members.teamId=?',t.id);}
   const ownerCol=individual?'studentId':'teamId';const ownerVal=individual?u.id:t.id;const last=await one(`SELECT MAX(ordinal) as n FROM submissions WHERE ${ownerCol}=? AND experimentId=?`,ownerVal,exp.id);const ordinal=(last?.n||0)+1;need(ordinal<=3,'每个实验最多提交 3 次',409);const sid=id();const job=enqueue(u.id,'grade',{submissionId:sid,releaseId:r.id,revision:r.revision,experiment:exp,fileIds:b.fileIds,note:String(b.note||'').slice(0,20000),members:mem},k.courseId,k.id,t?.id||null);await db.batch([job.statement,stmt('INSERT INTO submissions(id,classId,teamId,studentId,experimentId,releaseId,mode,ordinal,members,fileIds,note,jobId,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',sid,k.id,t?.id||null,individual?u.id:null,exp.id,r.id,'formal',ordinal,json(mem),json(b.fileIds),String(b.note||'').slice(0,20000),job.id,now())]);return reply({id:sid});}
  if(path==='appeal'&&method==='POST'){const b:any=await req.json();const s=await one('SELECT * FROM submissions WHERE id=?',b.submissionId);need(s,'提交不存在',404);if(s.teamId)await team(s.teamId,u);else need(s.studentId===u.id);const g=await one('SELECT * FROM grades WHERE submissionId=?',s.id);need(g&&(g.published||s.mode==='practice'),'评分尚未发布',400);await run('INSERT INTO appeals(id,submissionId,userId,content,created) VALUES(?,?,?,?,?)',id(),s.id,u.id,text(b.content),now());return reply({ok:true});}
  if(path==='grade-action'&&method==='POST'){const b:any=await req.json();const s=await one('SELECT * FROM submissions WHERE id=?',b.submissionId);need(s,'提交不存在',404);const k=await one('SELECT * FROM classes WHERE id=?',s.classId);need(k.owner===u.id||u.role==='admin');const g=await one('SELECT * FROM grades WHERE submissionId=?',s.id);need(g,'尚无评分',400);let report=parse(g.report);const reason=text(b.reason);if(b.report){const r=await one('SELECT * FROM releases WHERE id=?',s.releaseId);const e=parse(r.content).experiments.find((e:any)=>e.id===s.experimentId);report=validateAssessment(b.report,e,false);}const mutations=[stmt('UPDATE grades SET report=?,published=1,updated=? WHERE submissionId=?',json(report),now(),s.id),record(u.id,'grade.review',s.id,{reason,before:parse(g.report),after:report})];if(b.appealId)mutations.push(stmt('UPDATE appeals SET status=\'resolved\',resolution=? WHERE id=? AND submissionId=?',reason,b.appealId,s.id));await db.batch(mutations);return reply({ok:true});}
  if(path==='job-action'&&method==='POST'){const b:any=await req.json();const j=await one('SELECT * FROM jobs WHERE id=?',b.id);need(j,'任务不存在',404);need(j.owner===u.id||u.role==='admin'||(j.classId&&await one('SELECT 1 FROM classes WHERE id=? AND owner=?',j.classId,u.id)));need(j.kind!=='email','邮件由系统管理');if(b.action==='cancel')await run('UPDATE jobs SET status=\'cancelled\',finished=? WHERE id=? AND status IN (\'queued\',\'running\')',now(),j.id);else {need(j.status==='failed','只能重试失败任务',409);if(j.kind==='draft'){const p=parse(j.payload);const c=await one('SELECT * FROM courses WHERE id=?',j.courseId);need(p.revision===c.revision,'草案已变更，请发送新消息',409);}await run('UPDATE jobs SET status=\'queued\',lease=NULL,error=NULL,finished=NULL WHERE id=?',j.id);}return reply({ok:true});}
  return reply({error:'接口不存在'},404);
 }catch(e:any){const constraint=/UNIQUE constraint|constraint failed/i.test(e.message);return reply({error:constraint?'操作与当前状态冲突：你可能已加入小组、座位已占用或该版本已提交。请刷新后重试。':e.message||'服务异常'},e.status||(constraint?409:400));}
}
