import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
export class AcpClient {
 constructor(command,args,{cwd,onUpdate=()=>{},timeout=600000}={}){this.seq=0;this.pending=new Map();this.onUpdate=onUpdate;this.timeout=timeout;this.text='';this.process=spawn(command,args,{cwd,stdio:['pipe','pipe','pipe'],shell:false,windowsHide:true});this.reader=createInterface({input:this.process.stdout});this.reader.on('line',line=>{try{this.receive(JSON.parse(line))}catch{/* Ignore non-protocol logging, never display to students. */}});this.process.stderr.on('data',()=>{});this.process.on('error',e=>this.fail(e));this.process.on('exit',code=>this.fail(Error('ACP 进程结束，退出码 '+code)));}
 send(x){this.process.stdin.write(JSON.stringify(x)+'\n')}
 fail(e){for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(e)}this.pending.clear();}
 receive(m){if(m.method){if(m.id!==undefined){if(m.method==='session/request_permission'){this.send({jsonrpc:'2.0',id:m.id,result:{outcome:{outcome:'cancelled'}}});}else this.send({jsonrpc:'2.0',id:m.id,error:{code:-32601,message:'Client method not supported'}});}else if(m.method==='session/update'){const u=m.params?.update;if(u?.sessionUpdate==='agent_message_chunk'&&u.content?.type==='text'){this.text+=u.content.text;if(this.text.length>2e6){this.fail(Error('Agent 输出超过限制'));this.close();}}this.onUpdate(u);}return;}const p=this.pending.get(m.id);if(p){clearTimeout(p.timer);this.pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}}
 request(method,params){return new Promise((resolve,reject)=>{const id=++this.seq;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('ACP 请求超时：'+method));},this.timeout);this.pending.set(id,{resolve,reject,timer});this.send({jsonrpc:'2.0',id,method,params});});}
 async run(cwd,prompt){const init=await this.request('initialize',{protocolVersion:1,clientCapabilities:{},clientInfo:{name:'course-loop',version:'1.0.0'}});if(init.protocolVersion!==1)throw Error('不支持的 ACP 协议版本');const session=await this.request('session/new',{cwd,mcpServers:[]});this.sessionId=session.sessionId;const response=await this.request('session/prompt',{sessionId:this.sessionId,prompt:[{type:'text',text:prompt}]});if(response?.stopReason&&response.stopReason!=='end_turn')throw Error('Agent 未正常完成：'+response.stopReason);return this.text;}
 cancel(){if(this.sessionId)this.send({jsonrpc:'2.0',method:'session/cancel',params:{sessionId:this.sessionId}})}
 close(){this.reader.close();this.process.kill();this.fail(Error('ACP 连接已关闭'));}
}
